Part A

In [144]:
import numpy as np

matrixA =  np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
matrixB =  np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
mmatrixC =  np.array([[2, 2, 2],[2, 2, 2],[2, 2, 2]])
mmatrixD =  np.array([[2, 2],[2, 2]])

for i in matrixA:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


Part B

i. Transposing a matrix is the process of flippig or rotating a matrix. The transpose of a matrix is obtained by interchanging rows into columns or columns to rows. For example, the second element in the first row in column A would move and become the second element in the first column. 

In [145]:
print("Transposed Matrix A:\n" + str(np.transpose(matrixA)))

Transposed Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Part C

In [146]:
print("A + B = \n" + str(matrixA + matrixB))
print()
print("A - B = \n" + str(matrixA - matrixB))
print()
print("A + C = \n" + str(matrixA + matrixC))
print()
print("A - C = \n" + str(matrixA - matrixC))

A + B = 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

A - B = 
[[0 0 0]
 [0 0 0]
 [0 0 0]]

A + C = 
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

A - C = 
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


ii.) When matrix D is added or subtracted with any of the other matrices, then it results in an error because the matrices are two different sizes. Matrix addition and subtraction work by adding elements that are in the same position, so the matrices must be exact same size.

Part D

i.) Scalar multiplaction is when a matrix is multiplied by a singe real number. In scalar multiplication, each entry in the matrix is multiplied by the given scalar.

In [147]:
print("A = \n" + str(matrixA))

print("")

print("2A = \n" + str(2 * matrixA))

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2A = 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


ii.) In element-wise multiplication, two matrices of the same size are muiltiplied together. Each element in matrix is multiplied to the corresponding element in the other matrix. The product of the matrices is a matrix of the same size as the input matrices.

In [148]:
print("A x B = \n" + str(matrixA * matrixB))

A x B = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


iii.) Dot products multiplication involves multiplying the rows in the first matrix by the second matrix. All the first matrix elements in the row are multiplied with their corresponding element in the column of the second matrix. These products are then summed and added to a new matrix start from the top left and moving the the right. The size of the product matrix is the rows of columns in the first matrix by the number of columns in the second matrix. For example, a 2 x 3 matrix multiplied with a 3 x 2 matrix would result in a 2x2 matrix.

In [149]:
print("A x B= \n" + str(np.dot(matrixA, matrixB)))

A x B= 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


iv.) Cross Product Multiplication is multiplication of vectors in $\R_3 $ whose product is a vector that is orgthogonal or perpendicular to the two vectors. For example, say $ A = [a_1, a_2, a_3]$ and $B = [b_1, b_2, b_3]$, the cross product of the matrices would be $$[a_2b_3 - b_2a_3, a_3b_1 - b_3a_1, a_1b_2 - b_1a_2] $$

In [150]:
print("A[0] x A[1] = " + str(np.cross(matrixA[0], matrixA[1])))
print()
print("A x C = \n" + str(np.cross(matrixA, matrixC)))


A[0] x A[1] = [-3  6 -3]

A x C = 
[[-2  4 -2]
 [-2  4 -2]
 [-2  4 -2]]


Part E

The identity matrix is the n x n matrix that is in Row Reduced Echelon Form with the pivots in all columns. This means that there are ones going across the diagonal and zeroes above and below all the the ones. The identity matrix of an existing matrix is the same size as the matrix but replace with ones and zeroes.

In [151]:
matrixI = np.array([[1,0,0], [0,1,0], [0,0,1]])
print("A x " + "I{}".format('\N{LATIN SUBSCRIPT SMALL LETTER A}') + "= \n" + str(np.dot(matrixA, matrixI)))

A x Iₐ= 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Part F

Matrix inversion is the determination of a matrix that can multiply with a matrix to create the identity matrix. In a 2x2 Matrix, the first and fourth elements are swapped, the second and third elements are multiplied by -1, and the matrix is multiplied by $\frac{1}{ad-bc}$. If a matrix is invertible, it implicates that the column and row vectors are linearly independent frome each other. 